# Generated by Django 3.2.8 on 2021-10-30 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211030_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart'),
        ),
    ]
