# Generated by Django 3.2.8 on 2021-10-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_orderitem_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='products',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='products',
            field=models.ManyToManyField(to='shop.Cart'),
        ),
    ]
